name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag europe-north1-docker.pkg.dev/quantcopilot/cloud-run-source-deploy/quantcopilot
          gcloud run deploy quantcopilot \
            --image europe-north1-docker.pkg.dev/quantcopilot/cloud-run-source-deploy/quantcopilot \
            --platform managed --region europe-north1 --allow-unauthenticated
